In [1]:
pip install html5lib

Requirement already satisfied: html5lib in c:\users\sando\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\sando\anaconda3\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\sando\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install bs4

Requirement already satisfied: bs4 in c:\users\sando\anaconda3\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\sando\anaconda3\lib\site-packages (from bs4) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\sando\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Importing Dependencies
import pandas as pd
import requests
from bs4 import BeautifulSoup
import Links as ls
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [4]:
print(ls.Team_Roster_2007_url)
print(ls.Team_Roster_2024_url)

https://www.baseball-reference.com/teams/COL/2007.shtml#appearances
https://www.baseball-reference.com/teams/COL/2024.shtml#appearances

In [5]:
roster_url = ls.Team_Roster_2024_url
response = requests.get(roster_url)

In [9]:
team_roster_2024 = pd.read_excel ("../Test_files/Rockies_24_appearances.xlsx")
team_roster_2024

,Name,Age,Birth,B,T,Ht,Wt,DoB,Yrs,G,...,CF,RF,OF,DH,PH,PR,WAR,Salary,Unnamed: 28,Name-additional
0,Adael Amador,21,do DO,B,R,"6' 0""",200,Apr 11 2003,1st,10,...,0,0,0,0,0,0,-0.4,740000.0,NaN,amadoad01
1,Jordan Beck,23,us US,R,R,"6' 2""",225,Apr 19 2001,1st,23,...,1,0,23,0,0,0,-0.6,740000.0,NaN,beckjo01
2,Jalen Beeks,30,us US,L,L,"5' 11""",215,Jul 10 1993,6,42,...,0,0,0,0,0,0,0.1,1675000.0,NaN,beeksja02
3,Jake Bird,28,us US,R,R,"6' 3""",200,Dec 4 1995,3,22,...,0,0,0,0,0,0,-0.3,745000.0,NaN,birdja01
4,Ty Blach,33,us US,R,L,"6' 1""",215,Oct 20 1990,7,16,...,0,0,0,0,0,0,0.4,909677.0,NaN,blachty01
5,Charlie Blackmon,37,us US,L,L,"6' 3""",221,Jul 1 1986,14,74,...,0,23,23,46,8,0,0.4,13000000.0,NaN,blackch02
6,Sean Bouchard,28,us US,R,R,"6' 3""",215,May 16 1996,3,30,...,0,17,29,1,1,0,-0.5,740000.0,NaN,bouchse01
7,Kris Bryant,32,us US,R,R,"6' 5""",230,Jan 4 1992,10,24,...,0,4,4,10,0,0,-0.6,28000000.0,NaN,bryankr01
8,Matt Carasiti,32,us US,R,R,"6' 2""",205,Jul 23 1991,4,7,...,0,0,0,0,0,0,-0.5,NaN,NaN,carasma01
9,Jake Cave,31,us US,L,L,"6' 0""",200,Dec 4 1992,7,76,...,4,51,71,1,8,2,0.1,1000000.0,NaN,caveja01
10,Angel Chivilli,21,do DO,R,R,"6' 2""",162,Jul 28 2002,1st,5,...,0,0,0,0,0,0,-0.1,740000.0,NaN,chivian01
11,John Curtiss,31,us US,R,R,"6' 5""",220,Apr 5 1993,7,1,...,0,0,0,0,0,0,-0.2,NaN,NaN,curtijo02
12,Noah Davis,27,us US,R,R,"6' 2""",195,Apr 22 1997,3,1,...,0,0,0,0,0,0,-0.1,740000.0,NaN,davisno01
13,Elias Díaz,33,ve VE,R,R,"6' 1""",223,Nov 17 1990,10,67,...,0,0,0,14,3,0,1.3,6000000.0,NaN,diazel01
14,Brenton Doyle,26,us US,R,R,"6' 4""",220,May 14 1998,2,92,...,90,0,90,2,0,1,2.5,742000.0,NaN,doylebr02
15,Ryan Feltner,27,us US,R,R,"6' 4""",190,Sep 2 1996,4,19,...,0,0,0,0,0,0,-0.7,745000.0,NaN,feltnry01
16,Kyle Freeland,31,us US,L,L,"6' 4""",204,May 14 1993,8,9,...,0,0,0,0,0,1,-0.4,15000000.0,NaN,freelky01
17,Austin Gomber,30,us US,L,L,"6' 5""",220,Nov 23 1993,6,18,...,0,0,0,0,0,0,1.6,3150000.0,NaN,gombeau01
18,Hunter Goodman,24,us US,R,R,"5' 11""",210,Oct 8 1999,2,42,...,0,19,21,7,6,1,-0.6,740000.0,NaN,goodmhu01
19,Tanner Gordon,26,us US,L,R,"6' 5""",215,Oct 26 1997,1st,2,...,0,0,0,0,0,0,-0.4,NaN,NaN,gordota01
20,Geoff Hartlieb,30,us US,R,R,"6' 5""",240,Dec 9 1993,5,5,...,0,0,0,0,0,0,-0.3,740000.0,NaN,hartlge01
21,Sam Hilliard,30,us US,L,L,"6' 4""",236,Feb 21 1994,6,15,...,3,4,12,2,0,4,0.0,NaN,NaN,hillisa01
22,Dakota Hudson,29,us US,R,R,"6' 5""",215,Sep 15 1994,7,17,...,0,0,0,0,0,0,-0.4,1500000.0,NaN,hudsoda02
23,Greg Jones,26,us US,B,R,"6' 0""",175,Mar 7 1998,1st,6,...,0,4,4,0,2,0,0.1,740000.0,NaN,jonesgr02
24,Nolan Jones,26,us US,L,R,"6' 4""",195,May 7 1998,3,49,...,0,0,45,2,1,1,-0.5,740000.0,NaN,jonesno01
25,Tyler Kinley,33,us US,R,R,"6' 4""",220,Jan 31 1991,7,42,...,0,0,0,0,0,0,-0.7,1300000.0,NaN,kinlety01
26,Matt Koch,33,us US,L,R,"6' 3""",215,Nov 2 1990,7,2,...,0,0,0,0,0,0,-0.4,NaN,NaN,kochma01
27,Peter Lambert,27,us US,R,R,"6' 2""",208,Apr 18 1997,4,18,...,0,0,0,0,0,0,0.0,1250000.0,NaN,lambepe01
28,Justin Lawrence,29,pa PA,R,R,"6' 3""",213,Nov 25 1994,4,33,...,0,0,0,0,0,0,-0.9,745000.0,NaN,lawreju01
29,Germán Márquez,29,ve VE,R,R,"6' 1""",230,Feb 22 1995,9,1,...,0,0,0,0,0,0,-0.1,10000000.0,NaN,marquge01
30,Ryan McMahon,29,us US,L,R,"6' 2""",219,Dec 14 1994,8,95,...,0,0,0,1,0,0,2.7,12000000.0,All-Star,mcmahry01
31,Nick Mears,27,us US,R,R,"6' 2""",200,Oct 7 1996,5,39,...,0,0,0,0,0,0,-0.2,750000.0,NaN,mearsni01
32,Anthony Molina,22,ve VE,R,R,"6' 1""",170,Jan 12 2002,1st,21,...,0,0,0,0,0,0,-0.4,740000.0,NaN,molinan01
33,Elehuris Montero,25,do DO,R,R,"6' 3""",235,Aug 17 1998,3,67,...,0,0,0,12,4,0,-1.4,745000.0,NaN,monteel01
34,Riley Pint,26,us US,R,R,"6' 5""",225,Nov 6 1997,2,1,...,0,0,0,0,0,0,-0.1,740000.0,NaN,pintri01
35,Cal Quantrill,29,ca CA,L,R,"6' 3""",195,Feb 10 1995,6,19,...,0,0,0,0,0,0,2.3,6550000.0,NaN,quantca01
36,Brendan Rodgers,27,us US,R,R,"6' 0""",204,Aug 9 1996,6,79,...,0,0,0,3,1,2,0.4,3200000.0,NaN,rodgebr02
37,Josh Rogers,29,us US,L,L,"6' 3""",211,Jul 10 1994,5,5,...,0,0,0,0,0,0,-0.1,740000.0,NaN,rogerjo01
38,Aaron Schunk,26,us US,R,R,"6' 1""",205,Jul 24 1997,1st,10,...,0,0,0,1,2,4,-0.4,NaN,NaN,schunaa01
39,Jacob Stallings,34,us US,R,R,"6' 5""",225,Dec 22 1989,9,51,...,0,0,0,1,5,0,1.0,1500000.0,NaN,stallja01
40,Michael Toglia,25,us US,B,L,"6' 5""",226,Aug 16 1998,3,51,...,0,15,15,0,0,0,0.9,742000.0,NaN,toglimi01
41,Ezequiel Tovar,22,ve VE,R,R,"6' 0""",162,Aug 1 2001,3,95,...,0,0,0,0,0,0,2.7,1714286.0,NaN,tovarez01
42,Alan Trejo,28,us US,R,R,"6' 2""",205,May 30 1996,4,28,...,0,0,0,1,3,3,-0.6,745000.0,NaN,trejoal01
43,Victor Vodnik,24,us US,R,R,"6' 0""",200,Oct 9 1999,2,41,...,0,0,0,0,0,0,0.6,742000.0,NaN,vodnivi01

In [10]:
roster_url = ls.Team_Roster_2007_url
response = requests.get(roster_url)

In [11]:
team_roster_2007 = pd.read_excel ("../Test_files/Rockies_24_appearances.xlsx")
team_roster_2007

,Name,Age,Birth,B,T,Ht,Wt,DoB,Yrs,G,...,CF,RF,OF,DH,PH,PR,WAR,Salary,Unnamed: 28,Name-additional
0,Adael Amador,21,do DO,B,R,"6' 0""",200,Apr 11 2003,1st,10,...,0,0,0,0,0,0,-0.4,740000.0,NaN,amadoad01
1,Jordan Beck,23,us US,R,R,"6' 2""",225,Apr 19 2001,1st,23,...,1,0,23,0,0,0,-0.6,740000.0,NaN,beckjo01
2,Jalen Beeks,30,us US,L,L,"5' 11""",215,Jul 10 1993,6,42,...,0,0,0,0,0,0,0.1,1675000.0,NaN,beeksja02
3,Jake Bird,28,us US,R,R,"6' 3""",200,Dec 4 1995,3,22,...,0,0,0,0,0,0,-0.3,745000.0,NaN,birdja01
4,Ty Blach,33,us US,R,L,"6' 1""",215,Oct 20 1990,7,16,...,0,0,0,0,0,0,0.4,909677.0,NaN,blachty01
5,Charlie Blackmon,37,us US,L,L,"6' 3""",221,Jul 1 1986,14,74,...,0,23,23,46,8,0,0.4,13000000.0,NaN,blackch02
6,Sean Bouchard,28,us US,R,R,"6' 3""",215,May 16 1996,3,30,...,0,17,29,1,1,0,-0.5,740000.0,NaN,bouchse01
7,Kris Bryant,32,us US,R,R,"6' 5""",230,Jan 4 1992,10,24,...,0,4,4,10,0,0,-0.6,28000000.0,NaN,bryankr01
8,Matt Carasiti,32,us US,R,R,"6' 2""",205,Jul 23 1991,4,7,...,0,0,0,0,0,0,-0.5,NaN,NaN,carasma01
9,Jake Cave,31,us US,L,L,"6' 0""",200,Dec 4 1992,7,76,...,4,51,71,1,8,2,0.1,1000000.0,NaN,caveja01
10,Angel Chivilli,21,do DO,R,R,"6' 2""",162,Jul 28 2002,1st,5,...,0,0,0,0,0,0,-0.1,740000.0,NaN,chivian01
11,John Curtiss,31,us US,R,R,"6' 5""",220,Apr 5 1993,7,1,...,0,0,0,0,0,0,-0.2,NaN,NaN,curtijo02
12,Noah Davis,27,us US,R,R,"6' 2""",195,Apr 22 1997,3,1,...,0,0,0,0,0,0,-0.1,740000.0,NaN,davisno01
13,Elias Díaz,33,ve VE,R,R,"6' 1""",223,Nov 17 1990,10,67,...,0,0,0,14,3,0,1.3,6000000.0,NaN,diazel01
14,Brenton Doyle,26,us US,R,R,"6' 4""",220,May 14 1998,2,92,...,90,0,90,2,0,1,2.5,742000.0,NaN,doylebr02
15,Ryan Feltner,27,us US,R,R,"6' 4""",190,Sep 2 1996,4,19,...,0,0,0,0,0,0,-0.7,745000.0,NaN,feltnry01
16,Kyle Freeland,31,us US,L,L,"6' 4""",204,May 14 1993,8,9,...,0,0,0,0,0,1,-0.4,15000000.0,NaN,freelky01
17,Austin Gomber,30,us US,L,L,"6' 5""",220,Nov 23 1993,6,18,...,0,0,0,0,0,0,1.6,3150000.0,NaN,gombeau01
18,Hunter Goodman,24,us US,R,R,"5' 11""",210,Oct 8 1999,2,42,...,0,19,21,7,6,1,-0.6,740000.0,NaN,goodmhu01
19,Tanner Gordon,26,us US,L,R,"6' 5""",215,Oct 26 1997,1st,2,...,0,0,0,0,0,0,-0.4,NaN,NaN,gordota01
20,Geoff Hartlieb,30,us US,R,R,"6' 5""",240,Dec 9 1993,5,5,...,0,0,0,0,0,0,-0.3,740000.0,NaN,hartlge01
21,Sam Hilliard,30,us US,L,L,"6' 4""",236,Feb 21 1994,6,15,...,3,4,12,2,0,4,0.0,NaN,NaN,hillisa01
22,Dakota Hudson,29,us US,R,R,"6' 5""",215,Sep 15 1994,7,17,...,0,0,0,0,0,0,-0.4,1500000.0,NaN,hudsoda02
23,Greg Jones,26,us US,B,R,"6' 0""",175,Mar 7 1998,1st,6,...,0,4,4,0,2,0,0.1,740000.0,NaN,jonesgr02
24,Nolan Jones,26,us US,L,R,"6' 4""",195,May 7 1998,3,49,...,0,0,45,2,1,1,-0.5,740000.0,NaN,jonesno01
25,Tyler Kinley,33,us US,R,R,"6' 4""",220,Jan 31 1991,7,42,...,0,0,0,0,0,0,-0.7,1300000.0,NaN,kinlety01
26,Matt Koch,33,us US,L,R,"6' 3""",215,Nov 2 1990,7,2,...,0,0,0,0,0,0,-0.4,NaN,NaN,kochma01
27,Peter Lambert,27,us US,R,R,"6' 2""",208,Apr 18 1997,4,18,...,0,0,0,0,0,0,0.0,1250000.0,NaN,lambepe01
28,Justin Lawrence,29,pa PA,R,R,"6' 3""",213,Nov 25 1994,4,33,...,0,0,0,0,0,0,-0.9,745000.0,NaN,lawreju01
29,Germán Márquez,29,ve VE,R,R,"6' 1""",230,Feb 22 1995,9,1,...,0,0,0,0,0,0,-0.1,10000000.0,NaN,marquge01
30,Ryan McMahon,29,us US,L,R,"6' 2""",219,Dec 14 1994,8,95,...,0,0,0,1,0,0,2.7,12000000.0,All-Star,mcmahry01
31,Nick Mears,27,us US,R,R,"6' 2""",200,Oct 7 1996,5,39,...,0,0,0,0,0,0,-0.2,750000.0,NaN,mearsni01
32,Anthony Molina,22,ve VE,R,R,"6' 1""",170,Jan 12 2002,1st,21,...,0,0,0,0,0,0,-0.4,740000.0,NaN,molinan01
33,Elehuris Montero,25,do DO,R,R,"6' 3""",235,Aug 17 1998,3,67,...,0,0,0,12,4,0,-1.4,745000.0,NaN,monteel01
34,Riley Pint,26,us US,R,R,"6' 5""",225,Nov 6 1997,2,1,...,0,0,0,0,0,0,-0.1,740000.0,NaN,pintri01
35,Cal Quantrill,29,ca CA,L,R,"6' 3""",195,Feb 10 1995,6,19,...,0,0,0,0,0,0,2.3,6550000.0,NaN,quantca01
36,Brendan Rodgers,27,us US,R,R,"6' 0""",204,Aug 9 1996,6,79,...,0,0,0,3,1,2,0.4,3200000.0,NaN,rodgebr02
37,Josh Rogers,29,us US,L,L,"6' 3""",211,Jul 10 1994,5,5,...,0,0,0,0,0,0,-0.1,740000.0,NaN,rogerjo01
38,Aaron Schunk,26,us US,R,R,"6' 1""",205,Jul 24 1997,1st,10,...,0,0,0,1,2,4,-0.4,NaN,NaN,schunaa01
39,Jacob Stallings,34,us US,R,R,"6' 5""",225,Dec 22 1989,9,51,...,0,0,0,1,5,0,1.0,1500000.0,NaN,stallja01
40,Michael Toglia,25,us US,B,L,"6' 5""",226,Aug 16 1998,3,51,...,0,15,15,0,0,0,0.9,742000.0,NaN,toglimi01
41,Ezequiel Tovar,22,ve VE,R,R,"6' 0""",162,Aug 1 2001,3,95,...,0,0,0,0,0,0,2.7,1714286.0,NaN,tovarez01
42,Alan Trejo,28,us US,R,R,"6' 2""",205,May 30 1996,4,28,...,0,0,0,1,3,3,-0.6,745000.0,NaN,trejoal01
43,Victor Vodnik,24,us US,R,R,"6' 0""",200,Oct 9 1999,2,41,...,0,0,0,0,0,0,0.6,742000.0,NaN,vodnivi01